name: Docker Image CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch (change if you use a different branch)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          cd ./client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .
      
      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          cd ../server/authentication-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
      
      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      # Step 7: Build the Docker image
      - name: Build Docker image
        run: |
          cd ../user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
      
      # Step 8: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
